---
name: Publish

on:
  push:
    tags:
      # After vMajor.Minor.Patch _anything_ is allowed (without "/") !
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'EmpaEconversion/neware-api'


    steps:
      # Uncomment the following steps to publish to PyPI using flit

      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      # - name: Install flit
      #   run: pip install flit~=3.12

      # - name: Build and publish
      #   run: flit publish
      #   env:
      #     FLIT_USERNAME: __token__
      #     FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - uses: softprops/action-gh-release@v0.1.14
        name: Create release
        with:
            generate_release_notes: true
